### ISSUE TITLE
Modify these exports

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#1]
https://github.com/celw10/minsight/blob/1d1d81e3ca4cfe14305d11d2a47a537db08bde08/src/App.tsx#L3

https://github.com/celw10/minsight/blob/1d1d81e3ca4cfe14305d11d2a47a537db08bde08/src/components/main.tsx#L7

```diff
- const Navigation = () => {
+ export const Navigation = () => {
```

```diff
- import comp from "./components/main"
+ import { Navigation, Footer } from "./components/main"

**Comment by celw10** [comment]
Complete.
