### ISSUE TITLE
Clean up types here

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#14]
https://github.com/celw10/minsight/blob/9a88b351581530866a6c75b5bc04fb0d3302a8b8/src/assets/esri/styling.tsx#L40

Read up on this:

https://steveholgado.com/typescript-types-from-arrays/

```ts
// menu object, toggle ArcGIS widgets
type Toolbars = {
    id: number;
    name: string; 
    fields: Array<string>;
}
export const toolList: Toolbars[] = [
    {id: 0, name: "Widgets", fields: ["sketch", "layers", "basemap"]},
    {id: 1, name: "Analysis", fields: ["Not", "Implemented"]},
    {id: 2, name: "Perspective", fields: ["2D", "3D"]},
]

// return list of nav menu tools
export function toolItems(toolList: Array<Toolbars>) {
```

**Comment by celw10** [comment]
I went through the article, and getting the types of arrays and objects make more sense to me. However, I was getting a type error when I attempted to implement this. However, the code seems fine after removing the initial _type toolbars_. Upon closer inspection DataRoomNav.tsx is inferring types correctly from toolList, thus I shouldn't need to hard type this in anyways (following our discussion from last night)?
