### ISSUE TITLE
Refactor menu items to use navigation

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#15]
- `/view/2d`: Render the appropriate items
 - `/view/3d`: Render the appropriate items
 - Refresh the page -- It should all still be like that

EXTRA HARD CHALLENGE (features as query params):

 - `/view/2d?feature=claims,cancelled_claims`: Render the appropriate features
 - Refresh the page -- It should all still be like that

**Comment by celw10** [comment]
I didn't make too much progress with this, but is the best way to achieve this by using local storage? I can save the boolean arrays this way on page refresh?

**Comment by ecumene** [comment]
Example: `https://localhost:5321/views/3d?filters=gis_claims_historical,gis_claims_explaination`

Would be mapped to: `{ filters: "gis_claims_historical,gis_claims_explaination" }` in react-router's useSearchParams hook

Which becomes your state, instead of the array of booleans

- [x] [Replace filters here with search params](https://github.com/celw10/minsight/blob/aa83bc4ae4c54f44e4e30053ce1c51b468922d1e/src/assets/esri/initmap.tsx#L24)
- [x] Use the [react-router search params](https://reactrouter.com/en/main/hooks/use-search-params) in place of the array of booleans you have currently

**Comment by celw10** [comment]
I have the search params implemented and boolean array(s) are no longer in use. I'm able to use a single searchParam and context instead of two useStates and two UseContexts.
