### ISSUE TITLE
Replace the search params context provider with a call to the search hook

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#19]
- [x] Remove the Search Params Context Provider
 - [x] Replace all instances of using that context provider with a call to the useSearchParams hook

**Example:**
https://github.com/celw10/minsight/blob/eb839274f714ef5fc1a7ec1fc5c4721905c7f5a4/src/assets/components/DataRoomAside.tsx#L21

**Comment by celw10** [comment]
Context is gone and my initial workaround with only useSearchParams seems to be working fine!
