### ISSUE TITLE
[OPTIONAL]: React-Router: Create the base routing for the page 

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#2]
- [x] A `/` page with an about you
 - [x] A `/map` page with the map in it

The headers and footers should be the same

![image](https://user-images.githubusercontent.com/6249465/235378652-9a3ee32b-efe5-48f8-9e2c-f40ac730cedb.png)

**Comment by celw10** [comment]
This is up and running. I also made an /account and /about page. I'm also consistently distributing header and footers for each page.
