### ISSUE TITLE
Remove the `active[]`

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#21]
Maybe we could just check if the filter is in the `dataFilter[]` directly?

https://github.com/celw10/minsight/blob/eb839274f714ef5fc1a7ec1fc5c4721905c7f5a4/src/assets/components/DataRoomAside.tsx#LL67C92-L67C92

**Comment by celw10** [comment]
I've implemented a workaround getting the SearchParams then .get() on the button name & checking to see if the current mapped item is in the search params.
