### ISSUE TITLE
Replace datafilter with a position independent filter

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#23]
https://github.com/celw10/minsight/blob/eb839274f714ef5fc1a7ec1fc5c4721905c7f5a4/src/assets/components/DataRoomAside.tsx#L29

```typescript
  const dataFilter = searchParams.filter(([_, key]) => key==="filters").slice(1)[0].split("-");
```

**Comment by celw10** [comment]
This version worked 

const dataFilter = params.filter(([key, _]) => key==='filters')[0].slice(1)[0].split('-');
