### ISSUE TITLE
GOAL: Make nav filters a component

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#25]
- [x] Consolidate both of them into one component
 - [x] Export their logic to the parent

[Composition vs. Inheritance](https://legacy.reactjs.org/docs/composition-vs-inheritance.html)

**Comment by celw10** [comment]
I think this is complete. I certainly could make it neater, but it is functional. 

The mess is with the contrasting tailwind CSS styles, I need to use the ClassNames function to simplify them.
