### ISSUE TITLE
[OPTIONAL]: Check out react-three-fiber

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#3]
[React three fiber](https://docs.pmnd.rs/react-three-fiber/getting-started/introduction)

![image](https://user-images.githubusercontent.com/6249465/235378967-254acf91-041e-4678-8d55-d5e580131082.png)

**Comment by celw10** [comment]
I have the example working on a new "3D Viewer" tab. I have to change "moduleResolution" from bundler to node in tsconfig.node.json to get it to work.
