### ISSUE TITLE
GOAL: Grab some example data and display it

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#4]
- [ ] Store some data from your API in `.json` files
 - [ ] `import mapData from "[name].json"` in a component
 - [ ] Display it on the map

**Comment by celw10** [comment]
I figured how to get the live mineral exploration claims from the Government! I went through the "network" tab under inspect, and landed at the same site you did when you showed me the network tool. I eventually realized this site is an ArcGIS data server, and I am using ArcGIS as an API for my maps. I can import this data into my project live along with other geospatial layers that receive live updates from the government.

**Comment by ecumene** [comment]
Very hype
