### ISSUE TITLE
Properly format the ArcGIS sidebar

### ISSUE THREAD

**Issue by ecumene** [celw10/minsight#8]
- [x] Properly format the sidebar
 - [x] Add new data from the government

**Comment by celw10** [comment]
I've added a aside and navbar within the data room section. The navbar is for toggling on/off tools or widgets in the API, and the aside, which will ultimately having similar code to the navbar, will be for toggling on/off data. I have a toggle solution for navbar API widgets which took a while to figure out. I'm implementing the useState hook and updating state on mousebutton clicks, accessing this state in the parent component, then back down to the ArcGIS API children as props. The problem now is re-rendering the div container when the state changes so these widgets are added to the Data Room immediately after a mouse button click. 

I'll continue picking at this...

**Comment by celw10** [comment]
I manged to figure out the toggle function. Toolbars are not complete, but I can now figure out how to implement this.

Haven't added additional data yet, that will have to wait for next week.
